#obj-$(CONFIG_ARCH_MSM8974) += htc_8974-panel.o

obj-$(CONFIG_MACH_M8) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WHL) += htc_m8-panel.o
obj-$(CONFIG_MACH_M8_WL) += htc_m8-panel.o
obj-$(CONFIG_MACH_B2_UL) += htc_b2-panel.o
obj-$(CONFIG_MACH_B2_WLJ) += htc_b2-panel.o
